pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
    #main page
    path('', views.index, name='index'),
    path('pizza1',views.pizza1, name='pizza1'),
    path('pizza1/<int:pizza2_id>/', views.pizza2, name='pizza2'),
    path('new_comment/<int:pizza2_id>/', views.new_comment, name='new_comment'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users/',include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from .import views

app_name = 'users'

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register')
]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """Type of pizzas."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a string representation of the model."""
        return self.name


class Topping(models.Model):
    """Specific types of pizzas"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        """Returns a string representation of the model."""
        return self.name
    

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Comments'

    def __str__(self):
        return f"{self.text[:50]}..."


class Image(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    image = models.ImageField()

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Comment, Image

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''}
        #widgets = {'text': forms.Textarea(attrs={'cols':80})}

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('pizza', 'image')

pizzas/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from pizzas.forms import CommentForm, ImageForm
from .models import Pizza, Topping, Comment, Image
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    # get post may on interview
    return render(request, 'pizzas/index.html')


def pizza1(request):
    pizza1 = Pizza.objects.order_by('date_added')

    context = {'pizza1':pizza1}

    return render(request, 'pizzas/pizza1.html', context)


def pizza2(request, pizza2_id):
    pizza2 = Pizza.objects.get(id=pizza2_id)

    toppings = pizza2.topping_set.all()
    comments = pizza2.comment_set.all()
    image  = Image.objects.get(pizza=pizza2)
    print(image)
    context = {'pizza2':pizza2, 'toppings':toppings, 'comments':comments, 'image':image}
    #context = {'pizza':pizza2, 'comments':comments}

    return render(request, 'pizzas/pizza2.html', context)


#@login_required
def new_comment(request, pizza2_id):
    pizza2 = Pizza.objects.get(id=pizza2_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza2
            new_comment.save()

            return redirect('pizzas:pizza2', pizza2_id=pizza2_id)
    
    context = {'form':form, 'pizza2':pizza2}
    return render(request, 'pizzas/new_comment.html', context)

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request,new_user)
            return redirect('pizzas:index')

    context = {'form':form}
    return render(request,'registration/register.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %} 

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pizzeria</title>

    {% bootstrap_css %} 
    {% bootstrap_javascript jquery='full' %} 
        
</head>
<body style="background-color:antiquewhite">
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index'%}">
            Pizzeria</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzas:pizza1'%}">
                        Pizzas</a></li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %} 
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}

            </ul>
        </div>

    

    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="pb-2 mb-2 border-bottom">
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>


</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% load static %}

{% block page_header %}

<style>
    .jumbotron {background-color: white;

    }
</style>

    <div class="jumbotron">
        <h1 class="display-3">Welcome to Pizzeria!</h1>

        <p class="lead">Best choose in the campus. if you want to make an order, please log in to 
            our page and choose what kind of Pizzas you want from menus.</p>
        
            <a class="btn btn-lg btn-primary" href="{% url 'pizzas:pizza1'%}"
                style="background:sienna; border-color: snow; color: snow"
                role="button">Choose your pizza here &raquo;</a></button>
    </div>

<img src="{% static 'pizzas/pizzria.jpg' %}" alt="Pizzeria" width="550" height="350">
<img src="{% static 'pizzas/pizzeria.jpg' %}" alt="Pizzeria" width="550" height="350">


{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza2' pizza2.id %}">{{pizza2}}</a></p>

<p>Add a new comment:</p>

<form action="{% url 'pizzas:new_comment' pizza2.id %}" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/pizza1.html
{% extends "pizzas/base.html" %}

{% block page_header %}
    <h1 style="color: saddlebrown;">Pizzas</h1>
{% endblock page_header %}

{% block content %}

<style>
    .jumbotron {background-color: white;

    }
</style>

<div class="jumbotron">
    <ul>
        {% for p in pizza1 %}

    
        <li><h3>
            <a href="{% url 'pizzas:pizza2' p.id %}" style="color: saddlebrown;">{{ p }}</a>
        </h3></li>
 
        {% empty %}
        <li><h3>No pizzas have been added yet.</h3></li>
        {% endfor %}
    </ul>
</div>


{% endblock content %}

pizzas/templates/pizzas/pizza2.html
{% extends "pizzas/base.html" %}
{% load static %}

{% block page_header %}
<h3 style="font-size:xx-large; color: saddlebrown;">{{ pizza2 }}</h3>
<p style="font-size:medium;">  - you can add below topping for your pizza.</p> 
{% endblock page_header %}


{% block content %}


<ul>
    {% for t in toppings %}

    <li><h3 style="font-size:medium;">
        {{ t }}
    </h3></li>
    {% empty %}
    <li><h3>No pizza's topping have been added yet.</h3></li>
    {% endfor %}
</ul>


<ul>
    <li><h3>
        <img src="{{ image.image.url }}" alt="Pizzeria" width="350" height="350">
    </h3></li>
</ul>


<p>
    <a href="{% url 'pizzas:new_comment' pizza2.id %}" style="color: saddlebrown;"> add a new comment</a>
</p>


{% for c in comments %}
<div class="card mb-3" style="background-color:floralwhite;">
    <h4 class="card-header">
        {{ c.date_added }}
    </h4>
    <div class="card-body">
        {{ c.text|linebreaks }}
    </div>
</div>

{% empty %}
<li> There are no comment for this pizza yet.</li>
{% endfor %}


{% endblock content %}